//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciribob.DCS.SimpleRadio.Standalone.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ciribob.DCS.SimpleRadio.Standalone.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon audio_headset {
            get {
                object obj = ResourceManager.GetObject("audio_headset", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap status_connected {
            get {
                object obj = ResourceManager.GetObject("status_connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap status_disconnected {
            get {
                object obj = ResourceManager.GetObject("status_disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap status_disconnected_error {
            get {
                object obj = ResourceManager.GetObject("status_disconnected_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap status_disconnected_game {
            get {
                object obj = ResourceManager.GetObject("status_disconnected_game", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party|118.500
        ///CAS|123.450
        ///A/A|124.00
        ///LogiReq|133.00
        ///MedEvac|134.00
        ///Refuel|136.00
        ///COMMAND|118.000
        ///ALPHA|126.000
        ///BRAVO|127.000
        ///CHARLIE|128.000
        ///DELTA|129.000
        ///AIR|120.00
        ///GROUND|125.00
        ///LOGISTICS|130.00
        ///UTILITY|131.00
        ///INDUSTRY|135.00
        ///Vice|120.10
        ///Chaos|120.30
        ///Nighthawks|120.50
        ///Defiant|120.60
        ///Phoenix|120.70
        ///Witcher|125.10
        ///Moon|125.30
        ///Cerberus|131.10
        ///Magellan|131.200
        ///Meridian|131.30
        ///Rogue|131.40
        ///Shinobi|131.50
        ///Cosmo|131.60
        ///Atlas|130.10
        ///Benevolence|130.50
        ///Fleet Svc|130.60
        ///RockRaid|135. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string vngd_channels {
            get {
                return ResourceManager.GetString("vngd_channels", resourceCulture);
            }
        }
    }
}
