// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: srs.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ciribob.DCS.SimpleRadio.Standalone.Client.Network {
  /// <summary>
  /// Service definition
  /// </summary>
  public static partial class SRSService
  {
    static readonly string __ServiceName = "srspb.SRSService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest> __Marshaller_srspb_ClientConnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse> __Marshaller_srspb_ServerConnectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo> __Marshaller_srspb_ClientInfo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> __Marshaller_srspb_ServerResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo> __Marshaller_srspb_RadioInfo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest> __Marshaller_srspb_ClientSyncRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse> __Marshaller_srspb_ServerSyncResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest> __Marshaller_srspb_ClientDisconnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty> __Marshaller_srspb_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings> __Marshaller_srspb_ServerSettings = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SubscribeRequest> __Marshaller_srspb_SubscribeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SubscribeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerUpdate> __Marshaller_srspb_ServerUpdate = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerUpdate.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse> __Method_Connect = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_srspb_ClientConnectRequest,
        __Marshaller_srspb_ServerConnectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> __Method_UpdateClientInfo = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateClientInfo",
        __Marshaller_srspb_ClientInfo,
        __Marshaller_srspb_ServerResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> __Method_UpdateRadioInfo = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRadioInfo",
        __Marshaller_srspb_RadioInfo,
        __Marshaller_srspb_ServerResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse> __Method_SyncClient = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SyncClient",
        __Marshaller_srspb_ClientSyncRequest,
        __Marshaller_srspb_ServerSyncResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> __Method_DisconnectClient = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DisconnectClient",
        __Marshaller_srspb_ClientDisconnectRequest,
        __Marshaller_srspb_ServerResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings> __Method_GetServerSettings = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetServerSettings",
        __Marshaller_srspb_Empty,
        __Marshaller_srspb_ServerSettings);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SubscribeRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerUpdate> __Method_SubscribeToUpdates = new grpc::Method<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SubscribeRequest, global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerUpdate>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeToUpdates",
        __Marshaller_srspb_SubscribeRequest,
        __Marshaller_srspb_ServerUpdate);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SrsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SRSService</summary>
    public partial class SRSServiceClient : grpc::ClientBase<SRSServiceClient>
    {
      /// <summary>Creates a new client for SRSService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SRSServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SRSService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SRSServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SRSServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SRSServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Initial client connection and authentication (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse Connect(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Initial client connection and authentication (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse Connect(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Connect, null, options, request);
      }
      /// <summary>
      /// Initial client connection and authentication (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse> ConnectAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Initial client connection and authentication (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerConnectResponse> ConnectAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Connect, null, options, request);
      }
      /// <summary>
      /// Client update (metadata, client info, position)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse UpdateClientInfo(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateClientInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client update (metadata, client info, position)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse UpdateClientInfo(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateClientInfo, null, options, request);
      }
      /// <summary>
      /// Client update (metadata, client info, position)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> UpdateClientInfoAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateClientInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client update (metadata, client info, position)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> UpdateClientInfoAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateClientInfo, null, options, request);
      }
      /// <summary>
      /// Client radio update (metadata, radio info)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse UpdateRadioInfo(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRadioInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client radio update (metadata, radio info)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse UpdateRadioInfo(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRadioInfo, null, options, request);
      }
      /// <summary>
      /// Client radio update (metadata, radio info)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> UpdateRadioInfoAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRadioInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client radio update (metadata, radio info)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> UpdateRadioInfoAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.RadioInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRadioInfo, null, options, request);
      }
      /// <summary>
      /// Client synchronization request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse SyncClient(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SyncClient(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client synchronization request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse SyncClient(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SyncClient, null, options, request);
      }
      /// <summary>
      /// Client synchronization request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse> SyncClientAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SyncClientAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client synchronization request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSyncResponse> SyncClientAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientSyncRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SyncClient, null, options, request);
      }
      /// <summary>
      /// Client disconnect (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse DisconnectClient(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DisconnectClient(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client disconnect (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse DisconnectClient(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DisconnectClient, null, options, request);
      }
      /// <summary>
      /// Client disconnect (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> DisconnectClientAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DisconnectClientAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Client disconnect (metadata)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerResponse> DisconnectClientAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ClientDisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DisconnectClient, null, options, request);
      }
      /// <summary>
      /// Server settings request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings GetServerSettings(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServerSettings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Server settings request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings GetServerSettings(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetServerSettings, null, options, request);
      }
      /// <summary>
      /// Server settings request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings> GetServerSettingsAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServerSettingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Server settings request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerSettings> GetServerSettingsAsync(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetServerSettings, null, options, request);
      }
      /// <summary>
      /// Server-to-client updates stream
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerUpdate> SubscribeToUpdates(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SubscribeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeToUpdates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Server-to-client updates stream
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.ServerUpdate> SubscribeToUpdates(global::Ciribob.DCS.SimpleRadio.Standalone.Client.Network.SubscribeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeToUpdates, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SRSServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SRSServiceClient(configuration);
      }
    }

  }
}
#endregion
